artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  URL: https://github.com/ldotmithu/Dataset/raw/main/winequality-red.zip
  local_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transfomation:
  root_dir: artifacts/data_transfomation
  data_path: artifacts/data_ingestion/winequality-red.csv

model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_transfomation/train.csv
  test_data_path: artifacts/data_transfomation/test.csv
  model_name: model.joblib


model_evaluation:
  root_dir : artifacts/model_evaluation
  test_data_path: artifacts/data_transfomation/test.csv
  model_path: artifacts/model_training/model.joblib
  metrics_name: artifacts/model_evaluation/metrics.json

